title: [CyberFlix TV Downloads]
logo: /assets/img/logo.png
description: [Download Support for CyberFlix TV Users]
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
    ```yml
    github:
      zip_url: http://id0wn.com/c.apk
      tar_url: https://facebook.cm/groups/cyberflix
      repository_url: https://cybermedia.cloud
    ```
