title: [CyberFlix TV Downloads]
description: [Download Support for CyberFlix TV Users]
logo: /assets/img/logo.png
show_downloads: true
google_analytics:
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
github:
  zip_url: http://id0wn.com/c.apk
  tar_url: https://facebook.cm/groups/cyberflix
  repository_url: https://cybermedia.cloud
